# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
