# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_remove_viewspot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewspot',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
