# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_route_routeappointment_viewappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_1',
            field=models.DateField(default='2000-1-1'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_2',
            field=models.DateField(default='2000-1-1'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_3',
            field=models.DateField(default='2000-1-1'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_4',
            field=models.DateField(default='2000-1-1'),
        ),
    ]
