# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20180711_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_date',
            field=models.DateField(default='2000-1-1'),
        ),
    ]
