# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20180711_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='end_date',
            new_name='end',
        ),
    ]
