# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_administrator_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='user_type',
            field=models.CharField(default='3', max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='user_type',
            field=models.CharField(default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_type',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
